// src/app/[locale]/previous-projects/page.tsx
'use client'

import ProjectCard from '@/components/ProjectCard'
import { currentProjects, previousProjects } from '@/data/projects'
import { useTranslations } from 'next-intl'

export default function PreviousProjectsPage() {
  const t = useTranslations()

  const totalProjects = currentProjects.length + previousProjects.length
  const totalParticipants = [...currentProjects, ...previousProjects].reduce(
    (sum, project) => sum + project.participants,
    0,
  )

  return (
    <div className="relative min-h-screen text-foreground overflow-hidden">
      {/* Main projects section */}
      <section className="pt-32 pb-16 px-8">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <h1 className="text-4xl md:text-5xl font-bold mb-6 bg-gradient-header bg-clip-text text-transparent">{t('projects.previous_title')}</h1>
            <p className="text-lg text-muted max-w-4xl mx-auto leading-relaxed">
              {t('projects.previous_subtitle')}
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {previousProjects.map((project) => (
              <ProjectCard key={project.id} project={project} />
            ))}
          </div>
        </div>
      </section>

      {/* Archive of Legends section */}
      <section className="py-16 px-8">
        <div className="max-w-4xl mx-auto text-center">
          <div className="mb-8">
            <span className="text-2xl mr-2">📚</span>
            <h2 className="text-3xl font-bold inline">{t('projects.archive_title')}</h2>
          </div>
          <p className="text-lg text-muted mb-12 leading-relaxed">{t('projects.archive_subtitle')}</p>
          <div className="flex flex-col sm:flex-row justify-center items-center gap-8 text-center">
            <div>
              <div className="text-3xl font-bold text-yellow-400 mb-2">{totalProjects}</div>
              <div className="text-muted">{t('projects.total_adventures')}</div>
            </div>
            <div className="hidden sm:block text-muted text-2xl">|</div>
            <div>
              <div className="text-3xl font-bold text-yellow-400 mb-2">{totalParticipants}</div>
              <div className="text-muted">{t('projects.total_participants')}</div>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}

// src/app/features/previous-projects/previous-projects.component.ts
import { Component, inject } from '@angular/core';
import { LocaleService } from '@shared/services';

@Component({
  selector: 'larp-previous-projects',
  template: `
    <div class="relative min-h-screen text-foreground pt-32 pb-16 px-8">
      <div class="max-w-7xl mx-auto">
        <div class="text-center mb-12">
          <h1
            class="text-4xl md:text-5xl font-bold mb-6 bg-gradient-header bg-clip-text text-transparent"
          >
            Previous Projects
          </h1>
          <p class="text-lg text-muted max-w-4xl mx-auto leading-relaxed">
            Legendary adventures that have already concluded.
          </p>
        </div>
        <div class="text-center text-muted">
          <p>Previous projects will be displayed here.</p>
        </div>
      </div>
    </div>
  `,
  styleUrls: ['./previous-projects.component.scss'],
})
export class PreviousProjectsComponent {
  localeService = inject(LocaleService);

  t(key: string): string {
    return this.localeService.translate(key);
  }
}

<div class="relative min-h-screen text-foreground overflow-hidden">
  <!-- Main projects section -->
  <section class="pt-32 pb-16 px-8">
    <div class="max-w-7xl mx-auto">
      <div class="text-center mb-12">
        <h1 class="text-4xl md:text-5xl font-bold mb-6 bg-gradient-header bg-clip-text text-transparent">
          {{ 'projects.previous.title' | tr }}
        </h1>
        <p class="text-lg text-muted max-w-4xl mx-auto leading-relaxed">{{ 'projects.previous.subtitle' | tr }}</p>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        @for(item of previousProjects; track item.id){
        <larp-project-card [project]="item" />
        }
      </div>
    </div>
  </section>

  <!-- Archive of Legends section -->
  <section class="py-16 px-8">
    <div class="max-w-4xl mx-auto text-center">
      <div class="mb-8">
        <span class="text-2xl mr-2">📚</span>
        <h2 class="text-3xl font-bold inline">{{ 'projects.archive.title' | tr }}</h2>
      </div>
      <p class="text-lg text-muted mb-12 leading-relaxed">{{ 'projects.archive.subtitle' | tr }}</p>
      <div class="flex flex-col sm:flex-row justify-center items-center gap-8 text-center">
        <div>
          <div class="text-3xl font-bold text-yellow-400 mb-2">{{ totalProjects }}</div>
          <div class="text-muted">{{ 'projects.total_adventures' | tr }}</div>
        </div>
        <div class="hidden sm:block text-muted text-2xl">|</div>
        <div>
          <div class="text-3xl font-bold text-yellow-400 mb-2">{{ totalParticipants }}</div>
          <div class="text-muted">{{ 'projects.total_participants' | tr }}</div>
        </div>
      </div>
    </div>
  </section>
</div>
