// src/app/features/about/about.component.ts
import { Component } from '@angular/core';
import { TranslatePipe } from '@shared/pipes';

@Component({
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.scss'],
  imports: [TranslatePipe],
})
export class AboutComponent {}

<div class="pt-16">
  <!-- Hero Section -->
  <section class="pt-16 px-8">
    <div class="max-w-4xl mx-auto text-center">
      <h1 class="text-4xl md:text-6xl font-bold mb-6 bg-gradient-header bg-clip-text text-transparent">
        {{ 'about.title' | tr }}
      </h1>
      <p class="text-xl md:text-2xl text-muted max-w-3xl mx-auto leading-relaxed">{{ 'about.subtitle' | tr }}</p>
    </div>
  </section>

  <!-- Our Mission Section -->
  <section class="pt-16 px-8">
    <div class="max-w-5xl mx-auto bg-card rounded-lg p-6 border border-border">
      <div class="text-center mb-12">
        <div class="mb-8">
          <span class="text-4xl mr-3">🌉</span>
          <h2 class="text-3xl md:text-4xl font-bold inline">{{ 'about.mission.title' | tr }}</h2>
        </div>
      </div>

      <div class="space-y-6 text-lg text-muted leading-relaxed">
        <p>{{ 'about.mission.description' | tr }}</p>
        <p>{{ 'about.mission.challenges' | tr }}</p>
        <p>{{ 'about.mission.vision' | tr }}</p>
      </div>
    </div>
  </section>

  <!-- What We Offer, Who We Are, Meet the Creator Grid -->
  <section class="pt-16 px-8">
    <div class="max-w-5xl mx-auto">
      <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <!-- What We Offer -->
        <div class="bg-card rounded-lg p-6 border border-border">
          <div class="text-center mb-8">
            <span class="text-4xl">🌐</span>
            <h3 class="text-2xl font-bold mt-4">{{ 'about.offer.title' | tr }}</h3>
          </div>

          <div class="space-y-4">
            <div class="flex items-start">
              <span class="text-accent mr-3 mt-1">⚡</span>
              <span class="text-muted">{{ 'about.offer.hosting' | tr }}</span>
            </div>
            <div class="flex items-start">
              <span class="text-accent mr-3 mt-1">⚡</span>
              <span class="text-muted">{{ 'about.offer.subdomains' | tr }}</span>
            </div>
            <div class="flex items-start">
              <span class="text-accent mr-3 mt-1">⚡</span>
              <span class="text-muted">{{ 'about.offer.templates' | tr }}</span>
            </div>
            <div class="flex items-start">
              <span class="text-accent mr-3 mt-1">⚡</span>
              <span class="text-muted">{{ 'about.offer.support' | tr }}</span>
            </div>
            <div class="flex items-start">
              <span class="text-accent mr-3 mt-1">⚡</span>
              <span class="text-muted">{{ 'about.offer.security' | tr }}</span>
            </div>
            <div class="flex items-start">
              <span class="text-accent mr-3 mt-1">⚡</span>
              <span class="text-muted">{{ 'about.offer.community' | tr }}</span>
            </div>
          </div>
        </div>

        <!-- Who We Are -->
        <div class="bg-card rounded-lg p-6 border border-border">
          <div class="text-center mb-8">
            <span class="text-4xl">👥</span>
            <h3 class="text-2xl font-bold mt-4">{{ 'about.who.title' | tr }}</h3>
          </div>

          <p class="text-muted leading-relaxed">{{ 'about.who.description' | tr }}</p>
        </div>

        <!-- Meet the Creator -->
        <div class="bg-card rounded-lg p-6 border border-border">
          <div class="text-center mb-8">
            <span class="text-4xl">👨‍💻</span>
            <h3 class="text-2xl font-bold mt-4">{{ 'about.creator.title' | tr }}</h3>
          </div>

          <div class="space-y-4">
            <p class="text-muted leading-relaxed text-sm">{{ 'about.creator.description' | tr }}</p>
            <p class="text-muted leading-relaxed text-sm">{{ 'about.creator.background' | tr }}</p>
            <p class="text-muted leading-relaxed text-sm">{{ 'about.creator.mission' | tr }}</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Call to Action Section -->
  <section class="pt-16 px-8">
    <div class="max-w-5xl mx-auto text-center">
      <div class="bg-card rounded-lg p-6 border border-accent">
        <h3 class="text-3xl font-bold mb-6">{{ 'about.cta.title' | tr }}</h3>
        <p class="text-lg text-muted mb-8 leading-relaxed">{{ 'about.cta.description' | tr }}</p>
        <div class="flex flex-col sm:flex-row gap-4 justify-center">
          <button href="#" variant="secondary">{{ 'about.cta.get_in_touch' | tr }}</button>
          <button href="#" variant="primary">{{ 'about.cta.view_examples' | tr }}</button>
        </div>
        <p class="text-muted mt-6 text-sm">
          {{ 'about.cta.contact' | tr }}
          <br />
          {{ 'about.cta.join' | tr }}
        </p>
      </div>
    </div>
  </section>
</div>

// src/app/[locale]/about/page.tsx
'use client'

import Button from '@/components/Button'
import { useTranslations } from 'next-intl'

export default function AboutPage() {
  const t = useTranslations()

  return (
    <div className="pt-16">
      {/* Hero Section */}
      <section className="pt-16 px-8">
        <div className="max-w-4xl mx-auto text-center">
          <h1 className="text-4xl md:text-6xl font-bold mb-6 bg-gradient-header bg-clip-text text-transparent">
            {t('about.title')}
          </h1>
          <p className="text-xl md:text-2xl text-muted max-w-3xl mx-auto leading-relaxed">{t('about.subtitle')}</p>
        </div>
      </section>

      {/* Our Mission Section */}
      <section className="pt-16 px-8">
        <div className="max-w-5xl mx-auto bg-card rounded-lg p-6 border border-border">
          <div className="text-center mb-12">
            <div className="mb-8">
              <span className="text-4xl mr-3">🌉</span>
              <h2 className="text-3xl md:text-4xl font-bold inline">{t('about.mission_title')}</h2>
            </div>
          </div>

          <div className="space-y-6 text-lg text-muted leading-relaxed">
            <p>{t('about.mission_description')}</p>
            <p>{t('about.mission_challenges')}</p>
            <p>{t('about.mission_vision')}</p>
          </div>
        </div>
      </section>

      {/* What We Offer, Who We Are, Meet the Creator Grid */}
      <section className="pt-16 px-8">
        <div className="max-w-5xl mx-auto">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* What We Offer */}
            <div className="bg-card rounded-lg p-6 border border-border">
              <div className="text-center mb-8">
                <span className="text-4xl">🌐</span>
                <h3 className="text-2xl font-bold mt-4">{t('about.offer_title')}</h3>
              </div>

              <div className="space-y-4">
                <div className="flex items-start">
                  <span className="text-accent mr-3 mt-1">⚡</span>
                  <span className="text-muted">{t('about.offer_hosting')}</span>
                </div>
                <div className="flex items-start">
                  <span className="text-accent mr-3 mt-1">⚡</span>
                  <span className="text-muted">{t('about.offer_subdomains')}</span>
                </div>
                <div className="flex items-start">
                  <span className="text-accent mr-3 mt-1">⚡</span>
                  <span className="text-muted">{t('about.offer_templates')}</span>
                </div>
                <div className="flex items-start">
                  <span className="text-accent mr-3 mt-1">⚡</span>
                  <span className="text-muted">{t('about.offer_support')}</span>
                </div>
                <div className="flex items-start">
                  <span className="text-accent mr-3 mt-1">⚡</span>
                  <span className="text-muted">{t('about.offer_security')}</span>
                </div>
                <div className="flex items-start">
                  <span className="text-accent mr-3 mt-1">⚡</span>
                  <span className="text-muted">{t('about.offer_community')}</span>
                </div>
              </div>
            </div>

            {/* Who We Are */}
            <div className="bg-card rounded-lg p-6 border border-border">
              <div className="text-center mb-8">
                <span className="text-4xl">👥</span>
                <h3 className="text-2xl font-bold mt-4">{t('about.who_title')}</h3>
              </div>

              <p className="text-muted leading-relaxed">{t('about.who_description')}</p>
            </div>

            {/* Meet the Creator */}
            <div className="bg-card rounded-lg p-6 border border-border">
              <div className="text-center mb-8">
                <span className="text-4xl">👨‍💻</span>
                <h3 className="text-2xl font-bold mt-4">{t('about.creator_title')}</h3>
              </div>

              <div className="space-y-4">
                <p className="text-muted leading-relaxed text-sm">{t('about.creator_description')}</p>
                <p className="text-muted leading-relaxed text-sm">{t('about.creator_background')}</p>
                <p className="text-muted leading-relaxed text-sm">{t('about.creator_mission')}</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Call to Action Section */}
      <section className="pt-16 px-8">
        <div className="max-w-5xl mx-auto text-center">
          <div className="bg-card rounded-lg p-6 border border-accent">
            <h3 className="text-3xl font-bold mb-6">{t('about.cta_title')}</h3>
            <p className="text-lg text-muted mb-8 leading-relaxed">{t('about.cta_description')}</p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button href="#" variant="secondary">
                {t('about.cta_get_in_touch')}
              </Button>
              <Button href="#" variant="primary">
                {t('about.cta_view_examples')}
              </Button>
            </div>
            <p className="text-muted mt-6 text-sm">
              {t('about.cta_contact')}
              <br />
              {t('about.cta_join')}
            </p>
          </div>
        </div>
      </section>
    </div>
  )
}
