// src/app/features/current-projects/current-projects.component.ts
import { Component, inject } from '@angular/core';
import { LocaleService } from '../../shared/services/locale.service';

@Component({
  selector: 'larp-current-projects',
  template: `
    <div class="relative min-h-screen text-foreground pt-32 pb-16 px-8">
      <div class="max-w-7xl mx-auto">
        <div class="text-center mb-12">
          <h1
            class="text-4xl md:text-5xl font-bold mb-6 bg-gradient-header bg-clip-text text-transparent"
          >
            Current Projects
          </h1>
          <p class="text-lg text-muted max-w-4xl mx-auto leading-relaxed">
            Upcoming LARP adventures currently hosted on Heimdal Portal.
          </p>
        </div>
        <div class="text-center text-muted">
          <p>Projects will be displayed here.</p>
        </div>
      </div>
    </div>
  `,
  styleUrl: './current-projects.component.css',
})
export class CurrentProjectsComponent {
  localeService = inject(LocaleService);

  t(key: string): string {
    return this.localeService.translate(key);
  }
}

<div class="text-foreground overflow-hidden">
  <!-- Main projects section -->
  <section class="pt-32 pb-16 px-8">
    <div class="max-w-7xl mx-auto">
      <div class="text-center mb-12">
        <h1 class="text-4xl md:text-5xl font-bold mb-6 bg-gradient-header bg-clip-text text-transparent">
          {{ 'projects.current.title' | tr }}
        </h1>
        <p class="text-lg text-muted max-w-2xl mx-auto leading-relaxed">{{ 'projects.current.subtitle' | tr }}</p>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        @for(item of currentProjects; track item.id){
        <larp-project-card [project]="item" />
        }
      </div>
    </div>
  </section>

  <!-- Want to Host Your LARP section -->
  <section class="py-16 px-8">
    <div class="max-w-4xl mx-auto text-center">
      <h2 class="text-4xl font-bold mb-6">{{ 'projects.host_cta.title' | tr }}</h2>
      <p class="text-lg text-muted mb-12 leading-relaxed">{{ 'projects.host_cta.subtitle' | tr }}</p>
      <div class="flex flex-col sm:flex-row gap-4 justify-center">
        <larp-button [routerLink]="['/contact']" variant="primary" [label]="'home.request_hosting' | tr" />
        <larp-button [routerLink]="['/about']" variant="secondary" [label]="'projects.learn_more' | tr" />
      </div>
    </div>
  </section>
</div>

// src/app/current-projects/page.tsx
'use client'

import Button from '@/components/Button'
import ProjectCard from '@/components/ProjectCard'
import { currentProjects } from '@/data/projects'
import { useI18n } from '@/lib/i18n'

export default function CurrentProjectsPage() {
  const { t } = useI18n()

  return (
    <div className="relative min-h-screen text-white overflow-hidden">
      {/* Main projects section */}
      <section className="pt-32 pb-16 px-8">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <h1 className="text-4xl md:text-5xl font-bold mb-6">{t('projects.current_title')}</h1>
            <p className="text-lg text-neutral-400 max-w-4xl mx-auto leading-relaxed">
              {t('projects.current_subtitle')}
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {currentProjects.map((project) => (
              <ProjectCard key={project.id} project={project} />
            ))}
          </div>
        </div>
      </section>

      {/* Want to Host Your LARP section */}
      <section className="py-16 px-8">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-4xl font-bold mb-6">{t('projects.host_cta_title')}</h2>
          <p className="text-lg text-neutral-400 mb-12 leading-relaxed">{t('projects.host_cta_subtitle')}</p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button href="#" variant="primary">
              {t('landing.request_hosting')}
            </Button>
            <Button href="#" variant="secondary">
              {t('projects.learn_more')}
            </Button>
          </div>
        </div>
      </section>
    </div>
  )
}
