// src/app/features/contact/contact.component.ts
import { Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { TranslatePipe } from '@shared/pipes';

@Component({
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.scss'],
  imports: [ReactiveFormsModule, TranslatePipe],
})
export class ContactComponent {
  private readonly fb = inject(FormBuilder);

  public submitStatus = '';
  public isSubmitting = false;
  public contactForm = this.fb.group({
    name: this.fb.control<string>('', [Validators.required, Validators.minLength(1)]),
    email: this.fb.control<string | null>(null, [Validators.required, Validators.email]),
    larpName: this.fb.control<string | null>(null, [Validators.required, Validators.minLength(2)]),
    message: this.fb.control<string | null>(null, [Validators.required, Validators.minLength(10)]),
  });

  onSubmit() {
    if (this.contactForm.valid) {
      this.isSubmitting = true;
      // In a real implementation, this would send the form data to a server
      console.log('Form submitted:', this.contactForm.value);

      // Simulate API call
      setTimeout(() => {
        this.isSubmitting = false;
        // Show success message or redirect
        alert('Form submitted successfully!');
        this.contactForm.reset();
      }, 2000);
    }
  }
}

<div class="pt-16">
  <!-- Header Section -->
  <section class="pt-16 px-8">
    <div class="max-w-4xl mx-auto text-center">
      <h1 class="text-4xl md:text-6xl font-bold mb-6 bg-gradient-header bg-clip-text text-transparent">
        {{ 'contact.title' | tr }}
      </h1>
      <p class="text-xl md:text-2xl text-muted mb-12 max-w-3xl mx-auto leading-relaxed">
        {{ 'contact.subtitle' | tr }}
      </p>
    </div>
  </section>

  <!-- Contact Form Section -->
  <section class="pt-16 px-8">
    <div class="max-w-5xl mx-auto">
      <div class="grid grid-cols-1 lg:grid-cols-2 gap-12">
        <!-- Send Message Form -->
        <div class="bg-card rounded-lg p-8 border border-border">
          <div class="text-center mb-8">
            <span class="text-4xl">💬</span>
            <h2 class="text-2xl font-bold mt-4 text-foreground">{{ 'contact.send_message' | tr }}</h2>
            <p class="text-muted mt-2">{{ 'contact.send_message_description' | tr }}</p>
          </div>

          @if (submitStatus === 'success') {
          <div class="mb-6 p-4 bg-green-800/20 border border-green-600 rounded-lg">
            <p class="text-green-300 text-sm">{{ 'contact.form_success' | tr }}</p>
          </div>
          } @else if (submitStatus === 'error') {
          <div class="mb-6 p-4 bg-red-800/20 border border-red-600 rounded-lg">
            <p class="text-red-300 text-sm">{{ 'contact.form_error' | tr }}</p>
          </div>
          }

          <form class="space-y-6" [formGroup]="contactForm">
            <!-- Name Field -->
            <div>
              <label htmlFor="name" class="block text-sm font-medium text-foreground mb-2">
                {{ 'contact.form.name.label' | tr }}
              </label>
              <input
                formControlName="name"
                type="text"
                id="name"
                name="name"
                [placeholder]="'contact.form.name.placeholder' | tr"
                autoComplete="name"
                [class]="`w-full px-4 py-3 border rounded-lg bg-background text-foreground placeholder-muted transition-colors ${contactForm.controls.name.dirty && contactForm.controls.name.invalid ? 'border-red-500' : 'border-border focus:border-accent' }`"
              />
              @if(contactForm.controls.name.errors && contactForm.controls.name.dirty){
              <p id="name-error" class="mt-1 text-sm text-red-400" role="alert">
                {{ 'contact.form.validation.name_required' | tr }}
              </p>
              }
            </div>

            <!-- Email Field -->
            <div>
              <label htmlFor="email" class="block text-sm font-medium text-foreground mb-2">
                {{ 'contact.form.email.label' | tr }}
              </label>
              <input
                formControlName="email"
                type="email"
                id="email"
                name="email"
                autoComplete="email"
                [placeholder]="'contact.form.email.placeholder' | tr"
                [class]="`w-full px-4 py-3 border rounded-lg bg-background text-foreground placeholder-muted transition-colors ${contactForm.controls.email.dirty && contactForm.controls.email.invalid ? 'border-red-500' : 'border-border focus:border-accent' }`"
              />
              @if(contactForm.controls.email.errors && contactForm.controls.email.dirty){
              <p id="email-error" class="mt-1 text-sm text-red-400" role="alert">
                {{ 'contact.form.validation.email_required' | tr }}
              </p>
              }
            </div>

            <!-- LARP Name Field -->
            <div>
              <label htmlFor="larpName" class="block text-sm font-medium text-foreground mb-2">
                {{ 'contact.form.larp_name.label' | tr }}
              </label>
              <input
                formControlName="larpName"
                type="text"
                id="larpName"
                name="larpName"
                autoComplete="off"
                [placeholder]="'contact.form.larp_name.placeholder' | tr"
                [class]="`w-full px-4 py-3 border rounded-lg bg-background text-foreground placeholder-muted transition-colors ${contactForm.controls.larpName.dirty && contactForm.controls.larpName.invalid ? 'border-red-500' : 'border-border focus:border-accent' }`"
              />
              @if(contactForm.controls.larpName.errors && contactForm.controls.larpName.dirty){
              <p id="larpName-error" class="mt-1 text-sm text-red-400" role="alert">
                {{ 'contact.form.validation.larp_name_required' | tr }}
              </p>
              }
            </div>

            <!-- Message Field -->
            <div>
              <label htmlFor="message" class="block text-sm font-medium text-foreground mb-2">
                {{ 'contact.form.message.label' | tr }}
              </label>
              <textarea
                formControlName="message"
                id="message"
                name="message"
                rows="6"
                autoComplete="off"
                [placeholder]="'contact.form.message.placeholder' | tr"
                [class]="`w-full px-4 py-3 border rounded-lg bg-background text-foreground placeholder-muted transition-colors resize-vertical ${contactForm.controls.message.dirty && contactForm.controls.message.invalid ? 'border-red-500' : 'border-border focus:border-accent' }`"
              ></textarea>
              @if(contactForm.controls.message.errors && contactForm.controls.message.dirty){
              <p id="message-error" class="mt-1 text-sm text-red-400" role="alert">
                {{ 'contact.form.validation.message_required' | tr }}
              </p>
              }
            </div>

            <!-- Submit Button -->
            <button variant="secondary" type="submit" [disabled]="isSubmitting" (click)="onSubmit()">
              📧 {{ (isSubmitting ? 'contact.form.sending' : 'contact.form.submit') | tr }}
            </button>
          </form>
        </div>

        <!-- Direct Contact & What We Need -->
        <div class="space-y-8">
          <!-- Direct Contact -->
          <div class="bg-card rounded-lg p-8 border border-border">
            <div class="text-center mb-8">
              <span class="text-4xl">📧</span>
              <h2 class="text-2xl font-bold mt-4 text-foreground">{{ 'contact.direct_contact' | tr }}</h2>
            </div>

            <div class="space-y-6">
              <div>
                <h3 class="text-lg font-semibold text-foreground mb-2">{{ 'contact.email.label' | tr }}</h3>
                <p class="text-accent text-lg">{{ 'contact.email.address' | tr }}</p>
              </div>

              <div>
                <h3 class="text-lg font-semibold text-foreground mb-2">{{ 'contact.response_time.label' | tr }}</h3>
                <p class="text-muted">{{ 'contact.response_time.value' | tr }}</p>
              </div>
            </div>
          </div>

          <!-- What We Need -->
          <div class="bg-card rounded-lg p-8 border border-border">
            <div class="text-center mb-8">
              <span class="text-4xl">🛡️</span>
              <h2 class="text-2xl font-bold mt-4 text-foreground">{{ 'contact.what_we_need' | tr }}</h2>
            </div>

            <div class="space-y-4">
              <div class="flex items-start">
                <span class="text-accent mr-3 mt-1">⚡</span>
                <span class="text-muted">{{ 'contact.need.larp_name' | tr }}</span>
              </div>
              <div class="flex items-start">
                <span class="text-accent mr-3 mt-1">⚡</span>
                <span class="text-muted">{{ 'contact.need.subdomain' | tr }}</span>
              </div>
              <div class="flex items-start">
                <span class="text-accent mr-3 mt-1">⚡</span>
                <span class="text-muted">{{ 'contact.need.participants' | tr }}</span>
              </div>
              <div class="flex items-start">
                <span class="text-accent mr-3 mt-1">⚡</span>
                <span class="text-muted">{{ 'contact.need.requirements' | tr }}</span>
              </div>
              <div class="flex items-start">
                <span class="text-accent mr-3 mt-1">⚡</span>
                <span class="text-muted">{{ 'contact.need.content' | tr }}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

// src/app/[locale]/contact/page.tsx
'use client'

import Button from '@/components/Button'
import { useTranslations } from 'next-intl'
import { useState } from 'react'

interface FormData {
  name: string
  email: string
  larpName: string
  message: string
}

interface FormErrors {
  name?: string
  email?: string
  larpName?: string
  message?: string
}

export default function ContactPage() {
  const t = useTranslations()
  const [formData, setFormData] = useState<FormData>({
    name: '',
    email: '',
    larpName: '',
    message: '',
  })
  const [errors, setErrors] = useState<FormErrors>({})
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [submitStatus, setSubmitStatus] = useState<'idle' | 'success' | 'error'>('idle')

  const validateEmail = (email: string): boolean => {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    return emailRegex.test(email)
  }

  const validateForm = (): boolean => {
    const newErrors: FormErrors = {}

    if (!formData.name.trim()) {
      newErrors.name = t('contact.form_validation_name_required')
    }

    if (!formData.email.trim()) {
      newErrors.email = t('contact.form_validation_email_required')
    } else if (!validateEmail(formData.email)) {
      newErrors.email = t('contact.form_validation_email_invalid')
    }

    if (!formData.larpName.trim()) {
      newErrors.larpName = t('contact.form_validation_larp_name_required')
    }

    if (!formData.message.trim()) {
      newErrors.message = t('contact.form_validation_message_required')
    } else if (formData.message.trim().length < 20) {
      newErrors.message = t('contact.form_validation_message_min_length')
    }

    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target
    setFormData((prev) => ({ ...prev, [name]: value }))

    // Clear error when user starts typing
    if (errors[name as keyof FormErrors]) {
      setErrors((prev) => ({ ...prev, [name]: undefined }))
    }
  }

  const handleSubmit = async () => {
    if (!validateForm()) {
      return
    }

    setIsSubmitting(true)
    setSubmitStatus('idle')

    try {
      // Simulate form submission (in real app, this would call an API)
      await new Promise((resolve) => setTimeout(resolve, 1000))

      // Reset form and show success
      setFormData({ name: '', email: '', larpName: '', message: '' })
      setSubmitStatus('success')
    } catch {
      setSubmitStatus('error')
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div className="pt-16">
      {/* Header Section */}
      <section className="pt-16 px-8">
        <div className="max-w-4xl mx-auto text-center">
          <h1 className="text-4xl md:text-6xl font-bold mb-6 bg-gradient-header bg-clip-text text-transparent">
            {t('contact.title')}
          </h1>
          <p className="text-xl md:text-2xl text-muted mb-12 max-w-3xl mx-auto leading-relaxed">
            {t('contact.subtitle')}
          </p>
        </div>
      </section>

      {/* Contact Form Section */}
      <section className="pt-16 px-8">
        <div className="max-w-5xl mx-auto">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
            {/* Send Message Form */}
            <div className="bg-card rounded-lg p-8 border border-border">
              <div className="text-center mb-8">
                <span className="text-4xl">💬</span>
                <h2 className="text-2xl font-bold mt-4 text-foreground">{t('contact.send_message')}</h2>
                <p className="text-muted mt-2">{t('contact.send_message_description')}</p>
              </div>

              {submitStatus === 'success' && (
                <div className="mb-6 p-4 bg-green-800/20 border border-green-600 rounded-lg">
                  <p className="text-green-300 text-sm">{t('contact.form_success')}</p>
                </div>
              )}

              {submitStatus === 'error' && (
                <div className="mb-6 p-4 bg-red-800/20 border border-red-600 rounded-lg">
                  <p className="text-red-300 text-sm">{t('contact.form_error')}</p>
                </div>
              )}

              <form className="space-y-6" onSubmit={handleSubmit}>
                {/* Name Field */}
                <div>
                  <label htmlFor="name" className="block text-sm font-medium text-foreground mb-2">
                    {t('contact.form_name_label')}
                  </label>
                  <input
                    type="text"
                    id="name"
                    name="name"
                    value={formData.name}
                    onChange={handleInputChange}
                    placeholder={t('contact.form_name_placeholder')}
                    autoComplete="name"
                    className={`w-full px-4 py-3 border rounded-lg bg-background text-foreground placeholder-muted transition-colors ${
                      errors.name ? 'border-red-500' : 'border-border focus:border-accent'
                    }`}
                    aria-describedby={errors.name ? 'name-error' : undefined}
                    aria-invalid={!!errors.name}
                  />
                  {errors.name && (
                    <p id="name-error" className="mt-1 text-sm text-red-400" role="alert">
                      {errors.name}
                    </p>
                  )}
                </div>

                {/* Email Field */}
                <div>
                  <label htmlFor="email" className="block text-sm font-medium text-foreground mb-2">
                    {t('contact.form_email_label')}
                  </label>
                  <input
                    type="email"
                    id="email"
                    name="email"
                    autoComplete="email"
                    value={formData.email}
                    onChange={handleInputChange}
                    placeholder={t('contact.form_email_placeholder')}
                    className={`w-full px-4 py-3 border rounded-lg bg-background text-foreground placeholder-muted transition-colors ${
                      errors.email ? 'border-red-500' : 'border-border focus:border-accent'
                    }`}
                    aria-describedby={errors.email ? 'email-error' : undefined}
                    aria-invalid={!!errors.email}
                  />
                  {errors.email && (
                    <p id="email-error" className="mt-1 text-sm text-red-400" role="alert">
                      {errors.email}
                    </p>
                  )}
                </div>

                {/* LARP Name Field */}
                <div>
                  <label htmlFor="larpName" className="block text-sm font-medium text-foreground mb-2">
                    {t('contact.form_larp_name_label')}
                  </label>
                  <input
                    type="text"
                    id="larpName"
                    name="larpName"
                    autoComplete="off"
                    value={formData.larpName}
                    onChange={handleInputChange}
                    placeholder={t('contact.form_larp_name_placeholder')}
                    className={`w-full px-4 py-3 border rounded-lg bg-background text-foreground placeholder-muted transition-colors ${
                      errors.larpName ? 'border-red-500' : 'border-border focus:border-accent'
                    }`}
                    aria-describedby={errors.larpName ? 'larpName-error' : undefined}
                    aria-invalid={!!errors.larpName}
                  />
                  {errors.larpName && (
                    <p id="larpName-error" className="mt-1 text-sm text-red-400" role="alert">
                      {errors.larpName}
                    </p>
                  )}
                </div>

                {/* Message Field */}
                <div>
                  <label htmlFor="message" className="block text-sm font-medium text-foreground mb-2">
                    {t('contact.form_message_label')}
                  </label>
                  <textarea
                    id="message"
                    name="message"
                    rows={6}
                    autoComplete="off"
                    value={formData.message}
                    onChange={handleInputChange}
                    placeholder={t('contact.form_message_placeholder')}
                    className={`w-full px-4 py-3 border rounded-lg bg-background text-foreground placeholder-muted transition-colors resize-vertical ${
                      errors.message ? 'border-red-500' : 'border-border focus:border-accent'
                    }`}
                    aria-describedby={errors.message ? 'message-error' : undefined}
                    aria-invalid={!!errors.message}
                  />
                  {errors.message && (
                    <p id="message-error" className="mt-1 text-sm text-red-400" role="alert">
                      {errors.message}
                    </p>
                  )}
                </div>

                {/* Submit Button */}
                <Button variant="secondary" type="submit" disabled={isSubmitting}>
                  📧 {isSubmitting ? t('contact.form_sending') : <>{t('contact.form_submit')}</>}
                </Button>
              </form>
            </div>

            {/* Direct Contact & What We Need */}
            <div className="space-y-8">
              {/* Direct Contact */}
              <div className="bg-card rounded-lg p-8 border border-border">
                <div className="text-center mb-8">
                  <span className="text-4xl">📧</span>
                  <h2 className="text-2xl font-bold mt-4 text-foreground">{t('contact.direct_contact')}</h2>
                </div>

                <div className="space-y-6">
                  <div>
                    <h3 className="text-lg font-semibold text-foreground mb-2">{t('contact.email_label')}</h3>
                    <p className="text-accent text-lg">{t('contact.email_address')}</p>
                  </div>

                  <div>
                    <h3 className="text-lg font-semibold text-foreground mb-2">{t('contact.response_time_label')}</h3>
                    <p className="text-muted">{t('contact.response_time')}</p>
                  </div>
                </div>
              </div>

              {/* What We Need */}
              <div className="bg-card rounded-lg p-8 border border-border">
                <div className="text-center mb-8">
                  <span className="text-4xl">🛡️</span>
                  <h2 className="text-2xl font-bold mt-4 text-foreground">{t('contact.what_we_need')}</h2>
                </div>

                <div className="space-y-4">
                  <div className="flex items-start">
                    <span className="text-accent mr-3 mt-1">⚡</span>
                    <span className="text-muted">{t('contact.need_larp_name')}</span>
                  </div>
                  <div className="flex items-start">
                    <span className="text-accent mr-3 mt-1">⚡</span>
                    <span className="text-muted">{t('contact.need_subdomain')}</span>
                  </div>
                  <div className="flex items-start">
                    <span className="text-accent mr-3 mt-1">⚡</span>
                    <span className="text-muted">{t('contact.need_participants')}</span>
                  </div>
                  <div className="flex items-start">
                    <span className="text-accent mr-3 mt-1">⚡</span>
                    <span className="text-muted">{t('contact.need_requirements')}</span>
                  </div>
                  <div className="flex items-start">
                    <span className="text-accent mr-3 mt-1">⚡</span>
                    <span className="text-muted">{t('contact.need_content')}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
