// src/app/Footer.tsx
'use client'

import Button from '@/components/Button'
import { useI18n } from '@/lib/i18n'
import Link from 'next/link'

export default function Footer() {
  const { t } = useI18n()

  const navItems = [
    { href: '/', label: t('nav.home') },
    { href: '/current-projects', label: t('nav.current') },
    { href: '/previous-projects', label: t('nav.previous') },
    { href: '/about', label: t('nav.about') },
    { href: '/contact', label: t('nav.contact') },
  ]

  return (
    <footer className="bg-card border-t border-border mt-16" role="contentinfo">
      <div className="container mx-auto px-4 py-12">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8">
          {/* Brand Section */}
          <section className="space-y-4">
            <Link href="/" className="flex items-center space-x-2">
              <div className="text-2xl font-bold text-accent">⚡</div>
              <span className="text-xl font-bold text-foreground">{t('footer.brand_title')}</span>
            </Link>
            <p className="text-neutral-300 text-sm leading-relaxed">{t('footer.brand_description')}</p>
            <p className="text-neutral-400 text-sm leading-relaxed">{t('footer.brand_mission')}</p>
            <div className="flex items-center space-x-6 pt-2" role="group" aria-label="Service statistics">
              <div className="flex items-center space-x-2">
                <span className="text-accent" aria-hidden="true">🎲</span>
                <span className="text-neutral-300 text-sm">{t('footer.stats_projects')}</span>
              </div>
              <div className="flex items-center space-x-2">
                <span className="text-accent" aria-hidden="true">♥</span>
                <span className="text-neutral-300 text-sm">{t('footer.stats_uptime')}</span>
              </div>
            </div>
          </section>

          {/* Quick Links Section */}
          <section className="space-y-4">
            <h3 className="text-lg font-semibold text-foreground">{t('footer.quick_links')}</h3>
            <nav className="space-y-2" aria-label="Footer navigation">
              {navItems.map((item) => (
                <Link
                  key={item.href}
                  href={item.href}
                  className="block text-neutral-300 hover:text-accent text-sm transition-colors focus:outline-none focus:ring-2 focus:ring-accent focus:ring-offset-2 rounded-sm"
                >
                  {item.label}
                </Link>
              ))}
            </nav>
          </section>

          {/* Contact Section */}
          <section className="space-y-4">
            <h3 className="text-lg font-semibold text-foreground">{t('footer.contact')}</h3>
            <address className="space-y-3 not-italic">
              <div className="flex items-center space-x-2">
                <span className="text-accent" aria-hidden="true">📧</span>
                <a
                  href="mailto:hosting@larps.dk"
                  className="text-neutral-300 hover:text-accent text-sm transition-colors focus:outline-none focus:ring-2 focus:ring-accent focus:ring-offset-2 rounded-sm"
                >
                  {t('footer.email')}
                </a>
              </div>
              <div className="flex items-center space-x-2">
                <span className="text-accent" aria-hidden="true">📞</span>
                <a 
                  href="tel:+4530238112" 
                  className="text-neutral-300 hover:text-accent text-sm transition-colors focus:outline-none focus:ring-2 focus:ring-accent focus:ring-offset-2 rounded-sm"
                >
                  {t('footer.phone')}
                </a>
              </div>
            </address>
            <div className="pt-2">
              <Button href="/contact" variant="secondary" className="text-sm px-6 py-2">
                {t('footer.get_started')}
              </Button>
            </div>
          </section>
        </div>

        {/* Bottom Section */}
        <div className="border-t border-border pt-6">
          <div className="flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">
            <div className="flex flex-col md:flex-row items-center space-y-2 md:space-y-0 md:space-x-4">
              <p className="text-neutral-400 text-sm">
                {t('footer.copyright')}
                <a
                  href="https://notahero.dk"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-accent hover:underline focus:outline-none focus:ring-2 focus:ring-accent focus:ring-offset-2 rounded-sm"
                >
                  {' ' + t('footer.company_link')}
                </a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>
  )
}

// src/app/shared/components/footer/footer.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { RouterModule } from '@angular/router';
import { TranslatePipe } from '@shared/pipes/tr.pipe';
import { LocaleService } from '@shared/services';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'larp-footer',
  imports: [RouterModule, TranslatePipe],
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss'],
})
export class FooterComponent {
  public navItems = inject(LocaleService).navItems;
}

<footer class="bg-card border-t border-border mt-16" role="contentinfo">
  <div class="container mx-auto px-4 py-12">
    <div class="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8">
      <section class="space-y-4">
        <a class="flex items-center space-x-2" [routerLink]="['/']"
          ><div class="text-2xl font-bold text-accent">⚡</div>
          <span class="text-xl font-bold text-foreground">{{ 'footer.brand.title' | tr }}</span></a
        >
        <p class="text-muted text-sm leading-relaxed">
          {{ 'footer.brand.description' | tr }}
        </p>
        <p class="text-muted text-sm leading-relaxed">
          {{ 'footer.brand.mission' | tr }}
        </p>
        <div class="flex items-center space-x-6 pt-2" aria-label="Service statistics">
          <div class="flex items-center space-x-2">
            <span class="text-accent" aria-hidden="true">🎲</span
            ><span class="text-muted text-sm">{{ 'footer.stats.projects' | tr }}</span>
          </div>
          <div class="flex items-center space-x-2">
            <span class="text-accent" aria-hidden="true">♥</span
            ><span class="text-muted text-sm">{{ 'footer.stats.uptime' | tr }}</span>
          </div>
        </div>
      </section>
      <section class="space-y-4">
        <h3 class="text-lg font-semibold text-foreground">{{ 'footer.quick_links' | tr }}</h3>
        <nav class="space-y-2" aria-label="Footer navigation">
          @for(item of navItems; track item.label){
          <a class="block text-muted hover:text-accent text-sm transition-colors rounded-sm" [routerLink]="item.href">
            {{ item.label | tr }}
          </a>
          }
        </nav>
      </section>
      <section class="space-y-4">
        <h3 class="text-lg font-semibold text-foreground">{{ 'footer.contact' | tr }}</h3>
        <address class="space-y-3 not-italic">
          <div class="flex items-center space-x-2">
            <span class="text-accent" aria-hidden="true">📧</span
            ><a
              [href]="'mailto:' + ('footer.email' | tr)"
              class="text-muted hover:text-accent text-sm transition-colors rounded-sm"
              >{{ 'footer.email' | tr }}</a
            >
          </div>
          <div class="flex items-center space-x-2">
            <span class="text-accent" aria-hidden="true">📞</span
            ><a
              [href]="'tel:' + ('footer.phone' | tr)"
              class="text-muted hover:text-accent text-sm transition-colors rounded-sm"
              >{{ 'footer.phone' | tr }}</a
            >
          </div>
        </address>
        <div class="pt-2">
          <a
            class="inline-flex items-center justify-center gap-2 whitespace-nowrap text-sm font-medium ring-offset-background disabled:pointer-events-none disabled:opacity-50 rounded-md transition-all duration-300 cursor-pointer bg-gradient-nordic px-8 py-3 text-white hover:shadow-glow transform text-sm px-6 py-2"
            aria-disabled="false"
            [routerLink]="['/contact']"
            >{{ 'footer.get_started' | tr }}</a
          >
        </div>
      </section>
    </div>
    <div class="border-t border-border pt-6 text-center text-neutral-400 text-sm">
      <span>{{ 'footer.copyright' | tr }}</span>
      <a
        [href]="'https://notahero.dk'"
        target="_blank"
        rel="noopener noreferrer"
        class="text-accent hover:underline rounded-sm"
      >
        {{ 'footer.company_link' | tr }}
      </a>
    </div>
  </div>
</footer>
