// src/app/components/footer/footer.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { LocaleService } from '../../services/locale.service';

@Component({
  selector: 'app-footer',
  imports: [CommonModule, RouterModule],
  template: `
    <footer class="bg-card border-t border-border py-12 px-8">
      <div class="max-w-7xl mx-auto">
        <div class="grid grid-cols-1 md:grid-cols-4 gap-8">
          <!-- Brand Section -->
          <div class="md:col-span-2">
            <div class="flex items-center space-x-2 mb-4">
              <div class="text-2xl font-bold text-accent">⚡</div>
              <span class="text-xl font-bold text-foreground">Heimdal Portal</span>
            </div>
            <p class="text-muted mb-4 max-w-md">
              {{ t('footer.brand_description') }}
            </p>
            <p class="text-muted text-sm">
              {{ t('footer.brand_mission') }}
            </p>
            <div class="flex items-center space-x-6 mt-6 text-sm text-muted">
              <span>{{ t('footer.stats_projects') }}</span>
              <span>{{ t('footer.stats_uptime') }}</span>
            </div>
          </div>

          <!-- Quick Links -->
          <div>
            <h3 class="font-semibold text-foreground mb-4">{{ t('footer.quick_links') }}</h3>
            <ul class="space-y-2 text-sm">
              <li><a routerLink="/" class="text-muted hover:text-accent transition-colors">{{ t('nav.home') }}</a></li>
              <li><a routerLink="/current-projects" class="text-muted hover:text-accent transition-colors">{{ t('nav.current') }}</a></li>
              <li><a routerLink="/previous-projects" class="text-muted hover:text-accent transition-colors">{{ t('nav.previous') }}</a></li>
              <li><a routerLink="/about" class="text-muted hover:text-accent transition-colors">{{ t('nav.about') }}</a></li>
            </ul>
          </div>

          <!-- Contact -->
          <div>
            <h3 class="font-semibold text-foreground mb-4">{{ t('footer.contact') }}</h3>
            <ul class="space-y-2 text-sm">
              <li>
                <a href="mailto:hosting@larps.dk" class="text-muted hover:text-accent transition-colors">
                  {{ t('footer.email') }}
                </a>
              </li>
              <li>
                <a href="tel:+4530238112" class="text-muted hover:text-accent transition-colors">
                  {{ t('footer.phone') }}
                </a>
              </li>
            </ul>
            <a routerLink="/contact" 
               class="inline-block mt-4 px-4 py-2 bg-accent text-white rounded-lg hover:bg-accent/90 transition-colors text-sm font-medium">
              {{ t('footer.get_started') }}
            </a>
          </div>
        </div>

        <!-- Copyright -->
        <div class="border-t border-border pt-8 mt-8 flex flex-col sm:flex-row justify-between items-center text-sm text-muted">
          <p>{{ t('footer.copyright') }}</p>
          <a href="#" class="text-muted hover:text-accent transition-colors mt-2 sm:mt-0">
            {{ t('footer.company_link') }}
          </a>
        </div>
      </div>
    </footer>
  `,
  styleUrl: './footer.component.css'
})
export class FooterComponent {
  localeService = inject(LocaleService);

  t(key: string): string {
    return this.localeService.translate(key);
  }
}

// src/app/[locale]/Footer.tsx
'use client'

import Button from '@/components/Button'
import { Link } from '@/i18n/navigation'
import { useTranslations } from 'next-intl'

export default function Footer() {
  const t = useTranslations()

  const navItems = [
    { href: '/', label: t('nav.home') },
    { href: '/current-projects', label: t('nav.current') },
    { href: '/previous-projects', label: t('nav.previous') },
    { href: '/about', label: t('nav.about') },
    { href: '/contact', label: t('nav.contact') },
  ]

  return (
    <footer className="bg-card border-t border-border mt-16" role="contentinfo">
      <div className="container mx-auto px-4 py-12">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8">
          {/* Brand Section */}
          <section className="space-y-4">
            <Link href="/" className="flex items-center space-x-2">
              <div className="text-2xl font-bold text-accent">⚡</div>
              <span className="text-xl font-bold text-foreground">{t('footer.brand_title')}</span>
            </Link>
            <p className="text-muted text-sm leading-relaxed">{t('footer.brand_description')}</p>
            <p className="text-muted text-sm leading-relaxed">{t('footer.brand_mission')}</p>
            <div className="flex items-center space-x-6 pt-2" aria-label="Service statistics">
              <div className="flex items-center space-x-2">
                <span className="text-accent" aria-hidden="true">
                  🎲
                </span>
                <span className="text-muted text-sm">{t('footer.stats_projects')}</span>
              </div>
              <div className="flex items-center space-x-2">
                <span className="text-accent" aria-hidden="true">
                  ♥
                </span>
                <span className="text-muted text-sm">{t('footer.stats_uptime')}</span>
              </div>
            </div>
          </section>

          {/* Quick Links Section */}
          <section className="space-y-4">
            <h3 className="text-lg font-semibold text-foreground">{t('footer.quick_links')}</h3>
            <nav className="space-y-2" aria-label="Footer navigation">
              {navItems.map((item) => (
                <Link
                  key={item.href}
                  href={item.href}
                  className="block text-muted hover:text-accent text-sm transition-colors rounded-sm"
                >
                  {item.label}
                </Link>
              ))}
            </nav>
          </section>

          {/* Contact Section */}
          <section className="space-y-4">
            <h3 className="text-lg font-semibold text-foreground">{t('footer.contact')}</h3>
            <address className="space-y-3 not-italic">
              <div className="flex items-center space-x-2">
                <span className="text-accent" aria-hidden="true">
                  📧
                </span>
                <a
                  href="mailto:hosting@larps.dk"
                  className="text-muted hover:text-accent text-sm transition-colors rounded-sm"
                >
                  {t('footer.email')}
                </a>
              </div>
              <div className="flex items-center space-x-2">
                <span className="text-accent" aria-hidden="true">
                  📞
                </span>
                <a
                  href="tel:+4530238112"
                  className="text-muted hover:text-accent text-sm transition-colors rounded-sm"
                >
                  {t('footer.phone')}
                </a>
              </div>
            </address>
            <div className="pt-2">
              <Button href="/contact" variant="secondary" className="text-sm px-6 py-2">
                {t('footer.get_started')}
              </Button>
            </div>
          </section>
        </div>

        {/* Bottom Section */}
        <div className="border-t border-border pt-6">
          <div className="flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">
            <div className="flex flex-col md:flex-row items-center space-y-2 md:space-y-0 md:space-x-4">
              <p className="text-neutral-400 text-sm">
                {t('footer.copyright')}
                <a
                  href="https://notahero.dk"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-accent hover:underline rounded-sm"
                >
                  {' ' + t('footer.company_link')}
                </a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>
  )
}
